# tasks file for docker
- include: centos.yml
- include: debian.yml

- name: make sure docker starts on boot
  service: 
    name: docker 
    enabled: yes 
    state: started
  tags: [docker]

- name: add docker group
  group :
    name: docker
    state: present
  tags: [docker]

- name: add ansible user to docker group
  user: 
    name: ansible
    groups: docker
    append: yes
  tags: [docker]

- name: install pip module six (pre-req)
  pip: 
    name: six 
    version: "1.9.0"
  tags: [docker]

- name: install docker-py
  pip:
    name: docker-py
  tags: [docker]
