---
# tasks file for install
# if system is old, we need to update all yum packages
- name: update yum
  yum: 
    name: "*"
    state: latest
  when: ansible_distribution == "CentOS" and
          (ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")
  tags: [install, update_all]

- name: update apt
  apt: upgrade=yes
  when: ansible_distribution == "Debian" 
  tags: [install, update_all]

- name: create ansible user
  user:
    name: ansible
    shell: /bin/bash
    password: "{{ upassword |password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
  tags: [install]

# Directory for ssh keys status of generation
- name: create ssh keys generate status directory
  file:
    path: "{{ssh_keys_generate_dir}}"
    owner: ansible
    group: ansible
    state: directory
  tags: [install]

- name: set true to status file after the ssh keys generation
  shell: 'echo "true" > {{ssh_keys_generate_dir}}/status'
  sudo_user: ansible
  tags: [install]

- name: add ssh key to ansible
  authorized_key: 
    user: ansible 
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: [install]

- name: open ssh port in firewall
  firewalld:
    zone: public
    permanent: true
    immediate: true 
    state: enabled
    port: "{{item}}/tcp"
  with_items:
  - "{{ansible_container_ssh_port}}"
  - "{{jenkins_ssh_port}}"
  - "{{gitblit_ssh_port}}"
  - "{{registry_ssh_port}}"
  - "{{nginx_ssh_port}}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags: [install]
 
- name: remove ssh key to root
  authorized_key: 
    user: root 
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: absent
  tags: [install, ssh-remove]
  
