---
# tasks file for hub

- name: gitblit container
  docker:
    name: hub_gitblit_1
    image: "polymont/gitblit"
    state: started
    ports:
    - "127.0.0.1:8080:8080"
    - "9418:9418"
    - "29418:29418"
    - "{{gitblit_ssh_port}}:22"
    docker_api_version: 1.18 
  notify:
  - stop nginx container
  tags: [gitblit, hub]

- name: registry container
  docker:
    name: hub_registry_1
    image: "polymont/registry"
    state: started
    ports:
    - "127.0.0.1:5000:5000"
    - "{{registry_ssh_port}}:22"
    volumes:
    - "{{docker_home}}/registry_data:/var/lib/registry"
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    docker_api_version: 1.18
  notify:
  - stop nginx container
  tags: [registry, hub]

- name: nginx container
  docker:
    name: hub_nginx_1
    image: "polymont/nginx"
    state: started
    ports:
    - "80:80"
    - "443:443"
    - "{{nginx_ssh_port}}:22"
    links:
    - hub_registry_1:registry
    - hub_gitblit_1:gitblit
    - jenkins:jenkins
    volumes:
    - "{{docker_home}}/certs/:/etc/nginx/conf.d"
    docker_api_version: 1.18
  tags: [nginx, hub]
    