---
# handlers file for common
- name: stop ansible container
  docker:
    name: ansible
    image: "polymont/ansible:centos7"
    state: stopped
    docker_api_version: 1.18
  tags: [ansible]
  notify: restart ansible container

- name: stop gitblit container
  docker:
    name: hub_gitblit_1
    image: "polymont/gitblit"
    state: stopped
    docker_api_version: 1.18
  tags: [gitblit, hub]
  notify: restart gitblit container

- name: stop jenkins container
  docker:
    name: jenkins
    image: "polymont/jenkins"
    state: stopped
    docker_api_version: 1.18
  tags: [jenkins, hub]
  notify: restart jenkins container

- name: stop registry container
  docker:
    name: hub_registry_1
    image: "polymont/registry"
    state: stopped
  tags: [registry, hub]
  notify: restart registry container

- name: stop nginx container
  docker:
    name: hub_nginx_1
    image: "polymont/nginx"
    state: absent
  notify: restart nginx container
  tags: [nginx, hub]

- name: check or build ansible image
  docker_image: 
    path: "{{ansible_dir}}"
    name: "polymont/ansible"
    tag: "centos7"
    state: build
  tags: [ansible]

- name: check or build ubuntu image
  docker_image: 
    path: "{{ubuntu_dir}}"
    name: "polymont/ubuntu"
    state: build
  tags: [ubuntu]
  notify: 
  - check or build java image

- name: check or build java image
  docker_image:
    path: "{{java_dir}}"
    name: "polymont/java"
    tag: jdk8
    state: build
  tags: [java]
  notify:
  - stop gitblit container
  - stop jenkins container
  - check or build gitblit image
  - check or build tomcat image

- name: check or build gitblit image
  docker_image:
    path: "{{gitblit_dir}}"
    name: "polymont/gitblit"
    state: build
  tags: [gitblit, hub]

- name: check or build tomcat image
  docker_image:
    path: "{{tomcat_dir}}"
    name: "polymont/tomcat"
    tag: "8"
    state: build
  tags: [tomcat]
  notify:
  - stop jenkins container
  - check or build jenkins image

- name: check or build jenkins image
  docker_image:
    path: "{{jenkins_dir}}"
    name: "polymont/jenkins"
    state: build
  tags: [jenkins, hub]

- name: check or build registry image
  docker_image: 
    path: "{{registry_dir}}"
    name: "polymont/registry" 
    state: build
  tags: [registry, hub]

- name: check or build nginx image
  docker_image: 
    path: "{{nginx_dir}}"
    name: "polymont/nginx" 
    state: build
  tags: [nginx, hub]

- name: restart ansible container
  docker:
    name: ansible
    image: "polymont/ansible:centos7"
    state: reloaded
    stdin_open: yes
    ports:
    - "{{ansible_container_ssh_port}}:22"
    volumes: 
    - "{{recettes_dir}}:/recettes"
    docker_api_version: 1.18
  tags: [ansible]

- name: restart gitblit container
  docker:
    name: hub_gitblit_1
    image: "polymont/gitblit"
    state: reloaded
    ports:
    - "127.0.0.1:8080:8080"
    - "9418:9418"
    - "29418:29418"
    - "{{gitblit_ssh_port}}:22"
    docker_api_version: 1.18 
  tags: [gitblit, hub]
  notify:
  - stop nginx container

- name: restart jenkins container
  docker:
    name: jenkins
    image: "polymont/jenkins"
    state: reloaded
    ports:
    - "127.0.0.1:9080:8080"
    - "{{jenkins_ssh_port}}:22"
    volumes:
    - "{{docker_home}}/jenkins_home:/var/jenkins_home:rw"
    docker_api_version: 1.18
  tags: [jenkins, hub]
  notify:
  - stop nginx container

- name: restart registry container
  docker:
    name: hub_registry_1
    image: "polymont/registry"
    state: reloaded
    ports:
    - "127.0.0.1:5000:5000"
    - "{{registry_ssh_port}}:22"
    volumes:
    - /docker/registry_data:/var/lib/registry
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    docker_api_version: 1.18
  tags: [registry, hub]
  notify:
  - stop nginx container

- name: restart nginx container
  docker:
    name: hub_nginx_1
    image: "polymont/nginx"
    state: reloaded
    ports:
    - "80:80"
    - "443:443"
    - "{{nginx_ssh_port}}:22"
    links:
    - hub_registry_1:registry
    - hub_gitblit_1:gitblit
    - jenkins:jenkins
    volumes:
    - "{{docker_home}}/certs/:/etc/nginx/conf.d"
    docker_api_version: 1.18 
  tags: [nginx, hub]
