---
# tasks file for gitblit

- name: create gitblit direcory
  file:
    path: "{{gitblit_dir}}"
    state: directory
  tags: [gitblit]

- name: copy add users exec file
  copy:
    src: add_users.sh
    dest: "{{gitblit_dir}}/add_users.sh"
    mode: a+x
  tags: [gitblit]

- name: copy gitblit dockerfile
  copy:
    src: Dockerfile
    dest: "{{gitblit_dir}}/Dockerfile"
  notify:
    - stop gitblit container
    - check or build gitblit image
  tags: [gitblit]

- name: check gitblit image
  docker_image:
    path: "{{gitblit_dir}}"
    name: "polymont/gitblit"
    state: present
  tags: [gitblit]
