CREATE TABLE XWING.RESTRICTION (
    id INT NOT NULL PRIMARY KEY,
    restriction_type_id INT NOT NULL,
    ship_size_id INT,
    faction_id INT);

ALTER TABLE XWING.RESTRICTION 
ADD CONSTRAINT FK_RESTRICTION_RESTRICTION_TYPE_ID FOREIGN KEY (restriction_type_id) REFERENCES XWING.RESTRICTION_TYPE (id);
ALTER TABLE XWING.RESTRICTION 
ADD CONSTRAINT FK_RESTRICTION_SHIP_SIZE_ID FOREIGN KEY (ship_size_id) REFERENCES XWING.SHIP_SIZE (id);
ALTER TABLE XWING.RESTRICTION 
ADD CONSTRAINT FK_RESTRICTION_FACTION_ID FOREIGN KEY (faction_id) REFERENCES XWING.FACTION (id);

insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 1, 3,null, 2);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 2, 3,null, 3);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 3, 3,null, 1);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 4, 2, 2,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 5, 2, 3,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 6, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 7, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 8, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 9, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 10, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 11, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 12, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 13, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 14, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 15, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 16, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 17, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 18, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 19, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 20, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 21, 1,null,null);
insert into XWING.RESTRICTION (ID,RESTRICTION_TYPE_ID,SHIP_SIZE_ID,FACTION_ID)
values ( 22, 1,null,null);


commit;
