---
# tasks file for ubuntu

- name: create ubuntu direcory
  file:
    path: "{{ubuntu_dir}}"
    state: directory
  tags: [ubuntu]

- name: copy ssh keys to ubuntu role
  command: "cp -u {{item}} {{ubuntu_dir}}"
  with_items:
    - ~/.ssh/id_rsa.pub
  tags: [ubuntu]
  when: generated.stdout == "true"

- name: copy ubuntu dockerfile
  copy: 
    src: Dockerfile
    dest: "{{ubuntu_dir}}/Dockerfile"
  notify: 
  - check or build ubuntu image
  tags: [ubuntu]

- name: check ubuntu image
  docker_image: 
    path: "{{ubuntu_dir}}"
    name: "polymont/ubuntu"
    state: present
  tags: [ubuntu]
