---
# master playbook for Devops
- hosts: docker-machines
  roles:
#  apply for all roles
   - {role: common}
   - {role: init}
   - {role: ubuntu}
   - {role: java}
   - {role: tomcat}
#  deploy ansible
   - {role: ansible}
#  deploy jenkins
   - {role: jenkins}
#  deploy gitblit
   - {role: gitblit}
#  deploy registry
   - {role: registry}
#  deploy nginx
   - {role: nginx}
#  start hub containers
   - {role: hub}
#  start the last role
   - {role: last}
