---
# tasks file for nginx

- name: create nginx direcory
  file:
    path: "{{nginx_dir}}"
    state: directory
  tags: [nginx]

- name: copy ssh keys to nginx role
  command: "cp -u {{item}} {{nginx_dir}}"
  with_items:
    - ~/.ssh/id_rsa.pub
  tags: [nginx]
  when: generated.stdout == "true"

- name: copy nginx dockerfile
  copy: 
    src: Dockerfile
    dest: "{{nginx_dir}}/Dockerfile"
  notify:
  - stop nginx container 
  - check or build nginx image
  tags: [nginx]

- name: check nginx image
  docker_image: 
    path: "{{nginx_dir}}"
    name: "polymont/nginx" 
    state: present
  tags: [nginx]
