---
# ansible playbook for ansible role

- name: create ansible direcory
  file:
    path: "{{ansible_dir}}"
    state: directory
  tags: [ansible]

- name: copy ssh keys to ansible role
  command: "cp -u {{item}} {{ansible_dir}}"
  with_items:
    - ~/.ssh/id_rsa.pub
    - ~/.ssh/id_rsa   
  tags: [ansible]
  when: generated.stdout == "true"

- name: copy ansible dockerfile
  copy:
    src: Dockerfile
    dest: "{{ansible_dir}}/Dockerfile"
  notify:
    - stop ansible container
    - check or build ansible image
  tags: [ansible]

- name: create ansible on centos 7 image
  docker_image: 
    path: "{{ansible_dir}}" 
    name: "polymont/ansible" 
    tag: "centos7"
    state: present
  tags: [ansible]

- name: create recettes directory
  file: 
    path: "{{recettes_dir}}" 
    state: directory
  tags: [ansible]
  # TODO: add all ansible project/playbooks...

- name: run ansible on centos7 container
  docker:
    name: ansible
    image: "polymont/ansible:centos7"
    state: started 
    stdin_open: yes
    ports:
    - "{{ansible_container_ssh_port}}:22"
    volumes: 
    - "{{recettes_dir}}:/recettes"
    docker_api_version: 1.18
  tags: [ansible]
